# UCS 547 — Accelerated Data Science  
## Lab Assignment 1  
### NumPy Fundamentals

**Name:** Tanishq  
**Course:** UCS 547 – Accelerated Data Science  
**Assignment:** Lab Assignment 1  
**Topic:** NumPy Array Operations




---



### Q1. Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print("Original:", arr)
print("Reversed:", reversed_arr)


Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]




---



### Q2. Compare two NumPy arrays
arr1 = [[1,2],[3,4]]
arr2 = [[1,2],[3,4]]


In [2]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

print("Element-wise comparison:\n", arr1 == arr2)
print("Arrays equal:", np.array_equal(arr1, arr2))


Element-wise comparison:
 [[ True  True]
 [ True  True]]
Arrays equal: True




---



### Q3. Find most frequent value and indices


In [3]:
# array x
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_freq = values[np.argmax(counts)]
indices = np.where(x == most_freq)

print("Array x most frequent:", most_freq)
print("Indices:", indices)

# array y
y = np.array([1,1,1,2,3,4,2,4,3,3])
values, counts = np.unique(y, return_counts=True)
most_freq = values[np.argmax(counts)]
indices = np.where(y == most_freq)

print("\nArray y most frequent:", most_freq)
print("Indices:", indices)


Array x most frequent: 1
Indices: (array([0, 5, 7, 8, 9]),)

Array y most frequent: 1
Indices: (array([0, 1, 2]),)




---



### Q4. Matrix operations
gfg = [[4,1,9],[12,3,1],[4,5,6]]


In [4]:
gfg = np.array([[4,1,9],
                [12,3,1],
                [4,5,6]])

print("Matrix:\n", gfg)

# total sum
print("\nTotal sum:", np.sum(gfg))

# row-wise sum
print("Row-wise sum:", np.sum(gfg, axis=1))

# column-wise sum
print("Column-wise sum:", np.sum(gfg, axis=0))


Matrix:
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Total sum: 45
Row-wise sum: [14 16 15]
Column-wise sum: [20  9 16]




---



## Conclusion
Basic NumPy operations such as reversing arrays, comparison,
frequency counting, and matrix summation were performed successfully.
These operations demonstrate efficient numerical computation using NumPy.




---

